window.ST_GLOSSARY = [
  {
    term:"KPI", reading:"ケーピーアイ", english:"Key Performance Indicator", englishReading:"キー・パフォーマンス・インディケーター",
    family:"戦略・評価", oneLine:"最終目標に向かって順調に進んでいるかを見る途中の指標。",
    meaning:"施策や業務の進捗・成果を測るために設定する重要業績評価指標。",
    memoryPoint:"KGI＝ゴール、KPI＝ゴールまでの途中経過。",
    examPoint:"経営戦略、IT戦略、投資効果、業務改善、システム導入効果の評価で使う。",
    trap:"会社の最終的な売上目標など、最終成果そのものをKPIとする選択肢に注意。最終目標は通常KGI。",
    topics:["経営戦略","IT戦略","投資評価","業務改善"], relatedWords:["KGI","CSF","ROI","SLA"],
    confusableWords:[{term:"KGI",point:"最終目標を測る指標。KPIは途中経過。"},{term:"CSF",point:"目標達成に重要な成功要因。KPIはその達成状況を測る。"}],
    usage:"受注率をKPIとして設定し、システム導入後の改善状況を継続評価する。"
  },
  {
    term:"KGI", reading:"ケージーアイ", english:"Key Goal Indicator", englishReading:"キー・ゴール・インディケーター",
    family:"戦略・評価", oneLine:"最終的にどこまで達成したかを見るゴールの指標。",
    meaning:"売上高、利益率、顧客継続率など、最終的な経営成果・目標の達成度を測る指標。",
    memoryPoint:"KGI＝最終ゴール、KPI＝途中のものさし。",
    examPoint:"経営目標、IT戦略の成果、事業目標と情報システム施策の整合性を問う論点で使う。",
    trap:"途中の活動量や進捗率をKGIとする選択肢に注意。それらはKPIになりやすい。",
    topics:["経営戦略","目標管理","効果測定"], relatedWords:["KPI","CSF","ROI"],
    confusableWords:[{term:"KPI",point:"KPIは最終目標までの途中経過を測る。"}],
    usage:"顧客継続率をKGIとし、その達成に必要な商談実施率をKPIとして管理する。"
  },
  {
    term:"CSF", reading:"シーエスエフ", english:"Critical Success Factor", englishReading:"クリティカル・サクセス・ファクター",
    family:"戦略・評価", oneLine:"目標達成のために絶対に外せない成功要因。",
    meaning:"経営目標や戦略を実現するうえで、特に重要となる成功要因。",
    memoryPoint:"CSF＝何が重要か、KPI＝それができているかを何で測るか。",
    examPoint:"戦略立案、KPI設計、経営課題から重点施策を絞る論点で使う。",
    trap:"CSFそのものを数値指標だと考えない。数値で測る役割はKPI。",
    topics:["経営戦略","目標管理","KPI設計"], relatedWords:["KGI","KPI"],
    confusableWords:[{term:"KPI",point:"CSFは成功要因、KPIは測定指標。"}],
    usage:"顧客対応速度をCSFと特定し、平均回答時間をKPIとして管理する。"
  },
  {
    term:"ROI", reading:"アールオーアイ", english:"Return on Investment", englishReading:"リターン・オン・インベストメント",
    family:"投資・評価", oneLine:"投資した金額に対して、どれだけ利益・効果を得たかを見る指標。",
    meaning:"投資額に対して得られた利益や効果の割合を示し、投資効率を比較・評価する指標。",
    memoryPoint:"ROI＝投資効率。金額の大きさではなく、投資に対するリターンを見る。",
    examPoint:"IT投資評価、施策の優先順位付け、費用対効果の説明で使う。",
    trap:"総コストを示すTCOや、時間価値を考慮するNPVと混同しない。",
    topics:["IT投資","費用対効果","優先順位"], relatedWords:["TCO","NPV","KPI"],
    confusableWords:[{term:"TCO",point:"TCOは保有期間全体の総コスト。ROIは投資効率。"},{term:"NPV",point:"NPVは将来キャッシュフローを現在価値に割り引いて評価する。"}],
    usage:"複数のIT投資案をROIで比較し、効果の高い施策を優先する。"
  },
  {
    term:"TCO", reading:"ティーシーオー", english:"Total Cost of Ownership", englishReading:"トータル・コスト・オブ・オーナーシップ",
    family:"投資・評価", oneLine:"導入してから使い終わるまでにかかる全部のコスト。",
    meaning:"初期導入費だけでなく、運用、保守、教育、更新、廃棄などを含む総保有コスト。",
    memoryPoint:"TCO＝買う値段ではなく、持ち続ける総額。",
    examPoint:"クラウドとオンプレミスの比較、調達方式、システム更改の費用比較で使う。",
    trap:"初期費用が安い方式が必ずTCOも安いとは限らない。",
    topics:["IT投資","調達","クラウド比較"], relatedWords:["ROI","NPV","SaaS"],
    confusableWords:[{term:"ROI",point:"ROIは投資効率、TCOは総保有コスト。"}],
    usage:"初期費用だけでなく運用・保守費を含むTCOで方式を比較する。"
  },
  {
    term:"NPV", reading:"エヌピーブイ", english:"Net Present Value", englishReading:"ネット・プレゼント・バリュー",
    family:"投資・評価", oneLine:"将来のお金を今の価値に直して、投資の得か損かを見る方法。",
    meaning:"将来得られるキャッシュフローを現在価値に割り引き、初期投資などを差し引いた正味現在価値。",
    memoryPoint:"NPV＞0なら、一般に投資価値がある方向。時間価値を考える。",
    examPoint:"長期投資、複数年にまたがるシステム投資の経済性評価で使う。",
    trap:"単純な利益率であるROIと違い、NPVはお金の時間価値を考慮する。",
    topics:["投資評価","キャッシュフロー","経済性評価"], relatedWords:["ROI","TCO"],
    confusableWords:[{term:"ROI",point:"ROIは投資効率、NPVは将来CFを現在価値に換算した正味価値。"}],
    usage:"複数年のキャッシュフローを見込む投資案はNPVで経済性を評価する。"
  },
  {
    term:"RFI", reading:"アールエフアイ", english:"Request for Information", englishReading:"リクエスト・フォー・インフォメーション",
    family:"企画・調達", oneLine:"正式な提案依頼の前に、市場や製品の情報を集める依頼。",
    meaning:"発注者が市場、技術、製品、候補事業者などの情報提供を求める文書・プロセス。",
    memoryPoint:"RFI＝まず情報収集、RFP＝具体的な提案募集。",
    examPoint:"システム企画、調達、ベンダ選定、RFP作成前の情報収集で使う。",
    trap:"要件を示して価格や実施方法まで具体提案させるのはRFP。",
    topics:["調達","ベンダ選定","システム企画"], relatedWords:["RFP","PoC"],
    confusableWords:[{term:"RFP",point:"RFIは情報収集、RFPは具体的な提案依頼。"}],
    usage:"RFP作成前にRFIを実施し、市場の標準機能や候補方式を把握する。"
  },
  {
    term:"RFP", reading:"アールエフピー", english:"Request for Proposal", englishReading:"リクエスト・フォー・プロポーザル",
    family:"企画・調達", oneLine:"要件を示して、ベンダに具体的な提案を求める文書。",
    meaning:"発注者が要求事項、条件、評価基準などを示し、候補事業者から具体的な提案を受けるための提案依頼書。",
    memoryPoint:"RFIで情報を集め、RFPで具体提案を求める。",
    examPoint:"調達、ベンダ選定、提案評価、システム導入計画で使う。",
    trap:"RFPは単なる製品カタログ収集ではない。要求・条件を示して提案を競わせる。",
    topics:["調達","ベンダ選定","提案評価"], relatedWords:["RFI","PoC","SLA"],
    confusableWords:[{term:"RFI",point:"RFIは市場情報の収集段階。RFPは具体提案を求める段階。"}],
    usage:"業務要件と評価基準をRFPに明示し、複数ベンダの提案を比較する。"
  },
  {
    term:"PoC", reading:"ピーオーシー", english:"Proof of Concept", englishReading:"プルーフ・オブ・コンセプト",
    family:"企画・調達", oneLine:"本格導入の前に、小さく試して本当に使えるか確かめること。",
    meaning:"新技術やアイデアが技術面・業務面で実現可能か、限定した範囲で検証する概念実証。",
    memoryPoint:"PoC＝作り込む前に「本当に成立するか」を確かめる。",
    examPoint:"新技術導入、AI活用、クラウド移行、投資判断前の実現性検証で使う。",
    trap:"完成品を作ることが目的ではない。検証したい仮説と評価基準を明確にする。",
    topics:["新技術","実現性検証","投資判断"], relatedWords:["RFI","RFP","ROI"],
    confusableWords:[{term:"プロトタイプ",point:"プロトタイプは試作品。PoCは概念や実現可能性の検証が主目的。"}],
    usage:"本格投資前にPoCを実施し、精度・処理時間・業務適合性を検証する。"
  },
  {
    term:"SLA", reading:"エスエルエー", english:"Service Level Agreement", englishReading:"サービス・レベル・アグリーメント",
    family:"サービス管理", oneLine:"サービスをどの水準で提供するかを利用者と提供者で合意したもの。",
    meaning:"可用性、応答時間、復旧時間など、サービス提供者と利用者の間で合意するサービス水準。",
    memoryPoint:"SLA＝サービス品質の約束。測れる指標で決める。",
    examPoint:"外部委託、クラウド利用、運用保守、サービス管理で使う。",
    trap:"社内目標値のSLOと、顧客・利用者との合意であるSLAを混同しない。",
    topics:["サービス管理","外部委託","クラウド"], relatedWords:["KPI","BCP","RTO"],
    confusableWords:[{term:"SLO",point:"SLOはサービス提供側の目標値として使われる。SLAは利用者との合意。"}],
    usage:"稼働率99.9％や障害時の応答時間をSLAとして合意する。"
  },
  {
    term:"BCP", reading:"ビーシーピー", english:"Business Continuity Plan", englishReading:"ビジネス・コンティニュイティ・プラン",
    family:"継続性", oneLine:"災害や障害が起きても重要業務を止めない・早く戻すための計画。",
    meaning:"災害、事故、感染症、大規模障害などの発生時にも重要業務を継続し、早期復旧するための事業継続計画。",
    memoryPoint:"BCP＝何を優先して事業を続けるか。ITだけの復旧計画ではない。",
    examPoint:"事業継続、リスク管理、災害対策、重要業務の優先順位付けで使う。",
    trap:"バックアップやシステム復旧だけでBCPと考えない。人、拠点、業務、取引先も含む。",
    topics:["事業継続","リスク管理","災害対策"], relatedWords:["BIA","RTO","RPO"],
    confusableWords:[{term:"DR",point:"DRは主にITシステムの災害復旧。BCPは事業全体の継続。"}],
    usage:"BIAで重要業務を特定し、優先順位に基づいてBCPを整備する。"
  },
  {
    term:"BIA", reading:"ビーアイエー", english:"Business Impact Analysis", englishReading:"ビジネス・インパクト・アナリシス",
    family:"継続性", oneLine:"業務が止まったら何がどれだけ困るかを分析すること。",
    meaning:"業務停止が売上、顧客、法令、社会的信用などへ与える影響を分析し、復旧優先順位を決めるための手法。",
    memoryPoint:"BIAで影響を分析 → 重要業務を決める → RTO/RPOやBCPにつなげる。",
    examPoint:"BCP策定、重要業務の特定、復旧優先順位、許容停止時間の設定で使う。",
    trap:"脅威そのものを洗い出すリスク分析と、停止影響を分析するBIAを混同しない。",
    topics:["BCP","業務影響","復旧優先順位"], relatedWords:["BCP","RTO","RPO"],
    confusableWords:[{term:"リスク分析",point:"リスク分析は発生可能性や影響を評価。BIAは業務停止による事業影響を中心に分析。"}],
    usage:"BIAを実施し、停止影響の大きい業務から復旧優先順位を設定する。"
  },
  {
    term:"RTO", reading:"アールティーオー", english:"Recovery Time Objective", englishReading:"リカバリー・タイム・オブジェクティブ",
    family:"継続性", oneLine:"障害発生から、何時間以内に復旧させるかという目標。",
    meaning:"災害や障害で業務・システムが停止した後、復旧を完了させるまでの目標時間。",
    memoryPoint:"RTO＝時間。どれくらいで戻すか。",
    examPoint:"BCP、DR、システム可用性、復旧方式の設計で使う。",
    trap:"失ってよいデータの時間幅を表すRPOと逆にしない。",
    topics:["BCP","復旧設計","可用性"], relatedWords:["RPO","BCP","BIA","SLA"],
    confusableWords:[{term:"RPO",point:"RPOはどの時点のデータまで戻せればよいか。RTOは復旧までの時間。"}],
    usage:"重要業務はRTOを2時間とし、要求を満たす復旧方式を設計する。"
  },
  {
    term:"RPO", reading:"アールピーオー", english:"Recovery Point Objective", englishReading:"リカバリー・ポイント・オブジェクティブ",
    family:"継続性", oneLine:"障害時に、何時間前までのデータなら失ってもよいかという目標。",
    meaning:"障害発生時に、どの時点のデータまで復旧できれば許容できるかを示す目標復旧時点。",
    memoryPoint:"RPO＝Point＝時点。データをどこまで戻すか。",
    examPoint:"バックアップ頻度、データ保護、BCP、DR設計で使う。",
    trap:"RTOは復旧に要する時間、RPOは許容できるデータ損失の時間幅。",
    topics:["BCP","バックアップ","データ保護"], relatedWords:["RTO","BCP","BIA"],
    confusableWords:[{term:"RTO",point:"RTOは復旧までの時間。RPOは復旧するデータの時点。"}],
    usage:"RPOを1時間と定め、1時間以内の間隔でデータを保全できる方式を採用する。"
  },
  {
    term:"BPR", reading:"ビーピーアール", english:"Business Process Re-engineering", englishReading:"ビジネス・プロセス・リエンジニアリング",
    family:"業務改革", oneLine:"今のやり方を前提にせず、業務の流れそのものを抜本的に作り直すこと。",
    meaning:"既存の組織や手順にとらわれず、業務プロセスを根本から見直し再設計する業務改革。",
    memoryPoint:"BPR＝効率化だけではなく、業務そのものを再設計。",
    examPoint:"DX、基幹システム刷新、業務集約、組織改革、標準化で使う。",
    trap:"紙をそのまま電子化するだけではBPRとは言いにくい。不要業務の廃止や流れの再設計が必要。",
    topics:["DX","業務改革","標準化"], relatedWords:["ERP","SaaS","KPI"],
    confusableWords:[{term:"業務改善",point:"業務改善は現行の枠内で改善する場合もある。BPRは抜本的な再設計。"}],
    usage:"現行手順をそのままシステム化せず、BPRで業務プロセスを再設計する。"
  },
  {
    term:"CRM", reading:"シーアールエム", english:"Customer Relationship Management", englishReading:"カスタマー・リレーションシップ・マネジメント",
    family:"顧客・業務", oneLine:"顧客情報と接点をまとめ、顧客との関係を強くする考え方・仕組み。",
    meaning:"顧客属性、購買履歴、問い合わせ、商談などを統合し、顧客関係の維持・強化に活用する仕組み。",
    memoryPoint:"CRM＝顧客との関係管理。営業活動だけに限定しない。",
    examPoint:"顧客戦略、マーケティング、顧客満足、営業・サポート情報の統合で使う。",
    trap:"営業担当者の案件管理中心のSFAと、顧客関係全体を扱うCRMを混同しない。",
    topics:["顧客戦略","マーケティング","営業支援"], relatedWords:["ERP","SCM","KPI"],
    confusableWords:[{term:"SFA",point:"SFAは営業活動支援が中心。CRMは顧客との関係全体を管理。"}],
    usage:"顧客の購買履歴と問い合わせ履歴をCRMで統合し、提案精度を高める。"
  },
  {
    term:"SCM", reading:"エスシーエム", english:"Supply Chain Management", englishReading:"サプライ・チェーン・マネジメント",
    family:"顧客・業務", oneLine:"調達から販売までのモノと情報の流れを全体最適する考え方。",
    meaning:"調達、生産、在庫、物流、販売までのサプライチェーン全体を連携させ、在庫やリードタイムを最適化する。",
    memoryPoint:"SCM＝部門最適ではなく、供給連鎖全体の最適化。",
    examPoint:"在庫削減、需給調整、物流改革、企業間連携、リードタイム短縮で使う。",
    trap:"自社の生産管理だけでなく、取引先を含む全体の流れを見る。",
    topics:["在庫管理","物流","需給調整"], relatedWords:["ERP","CRM","KPI"],
    confusableWords:[{term:"ERP",point:"ERPは企業内資源の統合管理、SCMは供給連鎖全体の最適化。"}],
    usage:"需要情報を共有し、SCM全体で在庫量と納期を最適化する。"
  },
  {
    term:"ERP", reading:"イーアールピー", english:"Enterprise Resource Planning", englishReading:"エンタープライズ・リソース・プランニング",
    family:"顧客・業務", oneLine:"会計・販売・生産など、会社の基幹情報を一つにつなぐ仕組み。",
    meaning:"企業の会計、販売、購買、生産、人事などの基幹業務と経営資源情報を統合管理する考え方・システム。",
    memoryPoint:"ERP＝企業内の基幹業務・資源を統合。",
    examPoint:"基幹システム刷新、全社標準化、データ一元化、経営情報の可視化で使う。",
    trap:"顧客関係に特化するCRMや、供給網全体を見るSCMとの対象範囲を区別する。",
    topics:["基幹システム","データ統合","標準化"], relatedWords:["CRM","SCM","BPR","SaaS"],
    confusableWords:[{term:"CRM",point:"CRMは顧客関係が中心。ERPは企業内の基幹業務全体。"},{term:"SCM",point:"SCMは調達から販売までの供給連鎖全体。"}],
    usage:"部門ごとに分散した基幹データをERPで統合し、経営情報を一元化する。"
  },
  {
    term:"API", reading:"エーピーアイ", english:"Application Programming Interface", englishReading:"アプリケーション・プログラミング・インターフェース",
    family:"システム・DX", oneLine:"システム同士が決められた方法で機能やデータをやり取りする窓口。",
    meaning:"ソフトウェアやシステムが、他のソフトウェアの機能・データを利用するための接続仕様・インタフェース。",
    memoryPoint:"API＝システム同士の正式な受け渡し口。画面を人が操作する連携とは違う。",
    examPoint:"システム連携、データ連携、マイクロサービス、SaaS連携、二重入力削減で使う。",
    trap:"APIがあれば何でも自由に接続できるわけではない。認証、権限、仕様、制限の確認が必要。",
    topics:["システム連携","データ連携","DX"], relatedWords:["SaaS","ERP","CRM"],
    confusableWords:[{term:"画面連携",point:"画面操作を自動化する方式とは異なり、APIは定められた接続仕様でデータや機能を呼び出す。"}],
    usage:"API連携でマスタ情報を自動連携し、部門間の二重入力をなくす。"
  },
  {
    term:"SaaS", reading:"サース", english:"Software as a Service", englishReading:"ソフトウェア・アズ・ア・サービス",
    family:"システム・DX", oneLine:"ソフトを自社で持たず、インターネット経由のサービスとして利用する形態。",
    meaning:"事業者が提供・運用するソフトウェアを、利用者がネットワーク経由でサービスとして利用するクラウドサービス形態。",
    memoryPoint:"SaaS＝完成したソフトをサービスとして使う。サーバを借りるIaaSとは違う。",
    examPoint:"クラウド活用、標準化、短期導入、運用負荷削減、サブスクリプション型調達で使う。",
    trap:"自由な個別改修が前提ではない。標準機能への業務適合、データ移行、契約終了時の扱いも確認する。",
    topics:["クラウド","調達","標準化"], relatedWords:["API","TCO","BPR","ERP"],
    confusableWords:[{term:"オンプレミス",point:"オンプレミスは自組織で設備を保有・管理。SaaSは事業者のソフトをサービス利用。"},{term:"IaaS",point:"IaaSはサーバ等の基盤をサービスとして利用。SaaSはアプリケーションまで提供される。"}],
    usage:"標準化できる業務はSaaSを活用し、短期導入と運用負荷削減を図る。"
  }
];